"""The content hub API, backing the client-first redesign at /content-generation.

Entirely separate from the six older routers. It reads the `cg_*` tables, which
services.content_generation_sync derives from the source tables. No route here
writes to anything the old app owns, and no old route reads anything here, so
the two stacks can run side by side indefinitely.

WHO OWNS THE CLIENT LIST. Command HQ does, and nothing here copies it.
`/clients` calls the HQ export live on every request and returns what it says,
exactly as the older forms' prefill dropdown does. `cg_clients` exists only so
runs and assets have something to hang off, so a client with no content has no
row here at all, which is true of most of the 361. That is why every count on
this API is allowed to be zero and why no route 404s for a client HQ knows and
we do not.

Every client-scoped route takes HQ's uuid, typed `uuid.UUID` so a malformed id
is a 422 from FastAPI rather than an InvalidTextRepresentation 500 from psycopg.

VOCABULARY. `content_type` is the tab (website, social, blog, logo, ads) and
`section` is the sub type inside it (pages, posts, reels, stories, reviews,
blogs, scratch, revamp, ads). v1 used `section` for the tab; nothing here does.

  GET  /clients                            the switcher, live from HQ
  GET  /clients/{client_id}/overview       tabs, counts and run history
  GET  /clients/{client_id}/assets         the items for one tab
  GET  /clients/{client_id}/draft          the last brief, for the form to open on
  POST /clients/{client_id}/runs           request a run; 202, generates behind it
  GET  /assets/{asset_id}                  one item with its version history
  POST /assets/{asset_id}/approve          sign-off, which only the hub records
  POST /assets/{asset_id}/restore          make an older version the active one
  POST /assets/{asset_id}/image            book artwork, only once copy is approved
  GET  /assets/{asset_id}/chat             one version's conversation
  POST /assets/{asset_id}/chat             append to it
  GET  /settings                           per-section item counts
  PUT  /settings/{section}                 set one, house or per client
  DEL  /settings/{section}                 drop a client override
  POST /sync                               re-derive content from the old tables

IMAGES ARE NEVER GENERATED BY A RUN. A run produces content assets only. Artwork
is booked afterwards through /assets/{id}/image, which refuses unless the copy it
would illustrate is approved. That is a server-side rule, not a hidden button:
copy nobody has read is exactly what you do not want a designer building from.
"""

import logging
import uuid
from datetime import datetime, timezone
from typing import Dict, List, Optional, Tuple

from fastapi import APIRouter, BackgroundTasks, Depends, HTTPException, Query
from sqlalchemy import and_, case, func, select
from sqlalchemy.orm import Session

from app import models, schemas
from app.database import SessionLocal, get_db
from app.schemas.content_generation import HubContentType, HubSection
from app.services.client_export_service import list_clients as hq_list_clients
from app.services import content_generation_settings as section_settings
from app.services import content_run
from app.services.content_generation_sync import sync_all

logger = logging.getLogger("app")

router = APIRouter(prefix="/api/content-generation", tags=["content-generation"])

#: Tab order and labels, exactly as the design lists them.
CONTENT_TYPE_LABELS = [
    (HubContentType.website, "Website Content"),
    (HubContentType.social, "Social Media"),
    (HubContentType.blog, "Blog"),
    (HubContentType.logo, "Logo"),
    (HubContentType.ads, "Meta Ads"),
]

#: Which sections each content type may contain, which is also the fixed set of
#: sub tabs for every content type except blog. Blog's sub tabs are the periods
#: that actually exist for the client, so its single section is never shown.
SECTIONS_BY_CONTENT_TYPE: Dict[str, Tuple[str, ...]] = {
    "website": ("pages",),
    "social": ("posts", "reels", "stories", "reviews"),
    "blog": ("blogs",),
    "logo": ("scratch", "revamp"),
    "ads": ("ads",),
}

#: Layout flags per content type, matching the prototype's SECTIONS array.
CONTENT_TYPE_FLAGS: Dict[str, dict] = {
    "website": {"single": True, "table": True, "unit": "page groups"},
    "social": {"unit": "items"},
    "blog": {"monthly": True, "unit": "blogs"},
    "logo": {"logo": True, "unit": "logos"},
    "ads": {"single": True, "unit": "ads"},
}

SECTION_LABELS = {
    "pages": "Page groups",
    "posts": "Posts",
    "reels": "Reels",
    "stories": "Stories",
    "reviews": "Reviews",
    "blogs": "Blogs",
    "scratch": "From scratch",
    "revamp": "Revamp existing",
    "ads": "Ads",
}

_MONTHS = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
]

_HISTORY_LIMIT = 20


def _month_label(period: str) -> str:
    """'2026-09' as 'September 2026', falling back to the raw value.

    The check constraint on cg_runs.period makes the bad case unreachable
    through this app, but a hand-written row should show as itself rather than
    take the panel down.
    """
    try:
        year, month = period.split("-")
        return f"{_MONTHS[int(month) - 1]} {year}"
    except (ValueError, IndexError):
        return period


def _meta(count: int) -> str:
    if not count:
        return "No content yet"
    return "1 asset" if count == 1 else f"{count} assets"


def _hq_clients() -> List[dict]:
    """HQ's list, or an empty one if the export is unreachable.

    Only the overview uses this leniently: it needs a name for a client we hold
    no row for, and losing the name is a far better outcome than turning a
    working panel into a 502. `/clients` calls the export directly, because
    there the list IS the response.
    """
    try:
        return hq_list_clients()
    except Exception:
        logger.warning("content_hub_overview: HQ export unavailable, name omitted")
        return []


def _latest_run_ids(db: Session, client_id: uuid.UUID) -> List[uuid.UUID]:
    """The run that currently counts, for each content type and period.

    Re-running a content type creates a new version beside the old one, which is
    what makes the history meaningful. It also means "show me this client's
    social posts" has two possible answers, and showing both put v1 and v2 in
    one grid with nothing to tell them apart. The newest run wins; the older
    ones stay reachable through the run history.

    Partitioned by (content_type, period), NOT by content_type alone. Blog runs
    carry a period and its sub tabs ARE the months, so collapsing to one run per
    content type would hide every month but the newest. Every other content type
    has a null period, and a null partition key groups those together, so the
    same expression gives "latest per month" for blog and "latest overall" for
    the rest.

    row_number() rather than max(version) and a join back, because the join
    condition would have to match a null period against a null period, and
    `period = period` is never true for nulls. That failure would silently
    return no blog assets at all.
    """
    ranked = (
        db.query(
            models.ContentRun.run_id,
            func.row_number()
            .over(
                partition_by=[models.ContentRun.content_type, models.ContentRun.period],
                order_by=models.ContentRun.version.desc(),
            )
            .label("rank"),
        )
        .filter(models.ContentRun.client_id == client_id)
        .subquery()
    )
    return [
        row[0] for row in db.query(ranked.c.run_id).filter(ranked.c.rank == 1).all()
    ]


def _asset_counts(db: Session, client_id: uuid.UUID) -> List[Tuple[str, str, Optional[str], int]]:
    """Every count the overview needs, in one grouped query.

    Grouped by (content_type, section, period) so the tab totals, the section
    sub tabs and blog's per month sub tabs are all sums of the same rows. The
    alternative, a count per tab, is eleven round trips to render one panel.

    content_type lives on the run, not the asset, so this joins rather than
    reading a denormalised column that does not exist.
    """
    latest = _latest_run_ids(db, client_id)
    if not latest:
        return []
    return (
        db.query(
            models.ContentRun.content_type,
            models.ContentAsset.section,
            models.ContentRun.period,
            func.count(models.ContentAsset.asset_id),
        )
        .join(models.ContentAsset, models.ContentAsset.run_id == models.ContentRun.run_id)
        .filter(
            models.ContentAsset.client_id == client_id,
            # Latest runs only, so every badge matches the list it labels. A
            # badge counting superseded runs read "20" over a grid of 40.
            models.ContentRun.run_id.in_(latest),
        )
        .group_by(
            models.ContentRun.content_type,
            models.ContentAsset.section,
            models.ContentRun.period,
        )
        .all()
    )


def _blog_periods(db: Session, client_id: uuid.UUID) -> List[str]:
    """The months blog content exists for, newest first.

    Read off the runs rather than off the counts, so a month that was requested
    but produced nothing still gets a sub tab. An empty month is a real state
    the UI should be able to show.
    """
    return [
        period
        for (period,) in db.query(models.ContentRun.period)
        .filter(
            models.ContentRun.client_id == client_id,
            models.ContentRun.content_type == HubContentType.blog.value,
            models.ContentRun.period.isnot(None),
        )
        .distinct()
        .order_by(models.ContentRun.period.desc())
        .all()
    ]



def _asset_out(
    asset: models.ContentAsset,
    content_type: Optional[str] = None,
    body: Optional[str] = None,
    file_path: Optional[str] = None,
) -> schemas.HubAssetOut:
    """An asset row plus the content of its active version.

    content_type is coerced rather than assigned raw: Pydantic does not
    validate on assignment, so handing it the plain string an ENUM column
    returns would serialise with a warning instead of as the enum.
    """
    out = schemas.HubAssetOut.model_validate(asset)
    out.content_type = HubContentType(content_type) if content_type else None
    out.body = body
    out.file_path = file_path
    return out


def _get_asset(db: Session, asset_id: uuid.UUID) -> models.ContentAsset:
    asset = db.get(models.ContentAsset, asset_id)
    if asset is None:
        raise HTTPException(status_code=404, detail="Asset not found")
    return asset


def _get_version(
    db: Session, asset_id: uuid.UUID, version: int
) -> models.ContentAssetVersion:
    """The version row, or a 404.

    Every write that names a version goes through here. cg_asset_chats has a
    composite foreign key to (asset_id, version), so an unchecked bad version
    would fail at commit as an IntegrityError 500 rather than telling the
    caller which of the two ids was wrong.
    """
    row = db.get(
        models.ContentAssetVersion, {"asset_id": asset_id, "version": version}
    )
    if row is None:
        raise HTTPException(status_code=404, detail=f"Version {version} not found")
    return row


def _one_asset_out(db: Session, asset: models.ContentAsset) -> schemas.HubAssetOut:
    """`_asset_out` for the single asset routes, which have no joined row.

    Two lazy loads rather than the list route's single join. Worth it there,
    where the count is unbounded, pointless here, where it is one.
    """
    version = db.get(
        models.ContentAssetVersion,
        {"asset_id": asset.asset_id, "version": asset.active_version},
    )
    return _asset_out(
        asset,
        content_type=asset.run.content_type if asset.run else None,
        body=version.body if version else None,
        file_path=version.file_path if version else None,
    )


# --------------------------------------------------------------------------
# Clients
# --------------------------------------------------------------------------


@router.get("/clients", response_model=List[schemas.HubClientOut])
def list_clients(db: Session = Depends(get_db)):
    """Every client HQ has, with our asset count where we hold content.

    Live from the export on every call. Nothing is written and no client is
    created: the switcher is a view onto HQ's list, and the count is the only
    column this app owns. A count of zero is the normal case.
    """
    # Latest runs only, matching the tab badges and the grids. Counting every
    # run made the picker say "40 assets" for a client whose panel then showed
    # 20, which is the same discrepancy one level up: a superseded run is
    # history, not content the client currently has.
    #
    # One window function over every client rather than the per-client helper in
    # a loop, which would be 361 queries to render one list.
    ranked = (
        db.query(
            models.ContentRun.run_id,
            func.row_number()
            .over(
                partition_by=[
                    models.ContentRun.client_id,
                    models.ContentRun.content_type,
                    models.ContentRun.period,
                ],
                order_by=models.ContentRun.version.desc(),
            )
            .label("rank"),
        )
        .subquery()
    )
    latest_any = db.query(ranked.c.run_id).filter(ranked.c.rank == 1).subquery()

    counts = dict(
        db.query(models.ContentAsset.client_id, func.count(models.ContentAsset.asset_id))
        .filter(models.ContentAsset.run_id.in_(select(latest_any.c.run_id)))
        .group_by(models.ContentAsset.client_id)
        .all()
    )
    # last_run_at travels on this same response rather than on a second
    # "recent clients" endpoint. The picker shows Recent and All as two tabs
    # over one list, so a second route would mean a second call to HQ for 361
    # rows to answer a question this one already has the data for.
    last_runs = dict(
        db.query(models.ContentClient.client_id, models.ContentClient.last_run_at)
        .filter(models.ContentClient.last_run_at.isnot(None))
        .all()
    )

    out = []
    for row in hq_list_clients():
        client_id = (row.get("clientId") or "").strip()
        name = (row.get("name") or "").strip()
        if not client_id or not name:
            continue
        # The count is keyed on a real uuid, so an export row whose id is not
        # one still lists, just with nothing attached.
        try:
            key = uuid.UUID(client_id)
        except ValueError:
            key = None
        count = counts.get(key, 0) if key else 0
        out.append(
            schemas.HubClientOut(
                client_id=client_id,
                client_name=name,
                client_organization=row.get("organizationId"),
                asset_count=count,
                last_run_at=last_runs.get(key) if key else None,
                meta=_meta(count),
            )
        )
    return out


@router.get("/clients/{client_id}/overview", response_model=schemas.HubOverviewOut)
def client_overview(client_id: uuid.UUID, db: Session = Depends(get_db)):
    """The tabs, their counts and the run history, in one call.

    Three queries total, whatever the client holds: the counts, blog's periods
    and the run history with its approval tallies.

    A client we hold nothing for is a 200 with every count at zero, not a 404.
    HQ owns the client list, so "this client exists and has no content" is an
    ordinary answer and the only one most of the 361 have.
    """
    local = db.get(models.ContentClient, client_id)
    counts = _asset_counts(db, client_id)
    periods = _blog_periods(db, client_id)

    content_types = []
    for content_type, label in CONTENT_TYPE_LABELS:
        key = content_type.value
        flags = CONTENT_TYPE_FLAGS[key]

        if content_type is HubContentType.blog:
            sections = [
                schemas.HubSectionOut(
                    id=period,
                    label=_month_label(period),
                    count=sum(n for ct, _, p, n in counts if ct == key and p == period),
                )
                for period in periods
            ]
        else:
            sections = [
                schemas.HubSectionOut(
                    id=section,
                    label=SECTION_LABELS[section],
                    count=sum(n for ct, s, _, n in counts if ct == key and s == section),
                )
                for section in SECTIONS_BY_CONTENT_TYPE[key]
            ]

        content_types.append(
            schemas.HubContentTypeOut(
                id=content_type,
                label=label,
                count=sum(n for ct, _, _, n in counts if ct == key),
                unit=flags["unit"],
                single=flags.get("single", False),
                table=flags.get("table", False),
                monthly=flags.get("monthly", False),
                logo=flags.get("logo", False),
                sections=sections,
            )
        )

    runs = _run_history(db, client_id)

    total = sum(n for _, _, _, n in counts)
    name = local.client_name if local else ""
    organization = str(local.client_organization) if local and local.client_organization else None
    if not name:
        # Only reached for a client we hold no row for, which is why the export
        # is not consulted in the common case.
        for row in _hq_clients():
            if (row.get("clientId") or "").strip() == str(client_id):
                name = (row.get("name") or "").strip()
                organization = row.get("organizationId")
                break

    return schemas.HubOverviewOut(
        client=schemas.HubClientOut(
            client_id=str(client_id),
            client_name=name,
            client_organization=organization,
            asset_count=total,
            meta=_meta(total),
        ),
        content_types=content_types,
        runs=runs,
    )


def _run_history(db: Session, client_id: uuid.UUID) -> List[schemas.HubRunOut]:
    """The newest runs with their "N of M approved" label.

    The tallies come back in one grouped query over the runs already fetched,
    rather than two counts per run, which is forty extra queries at this limit.
    """
    runs = (
        db.query(models.ContentRun)
        .filter(models.ContentRun.client_id == client_id)
        .order_by(models.ContentRun.created_at.desc())
        .limit(_HISTORY_LIMIT)
        .all()
    )
    if not runs:
        return []

    tallies = {
        run_id: (total, approved)
        for run_id, total, approved in db.query(
            models.ContentAsset.run_id,
            func.count(models.ContentAsset.asset_id),
            func.count(case((models.ContentAsset.status == "approved", 1))),
        )
        .filter(models.ContentAsset.run_id.in_([r.run_id for r in runs]))
        .group_by(models.ContentAsset.run_id)
        .all()
    }

    out = []
    for run in runs:
        total, approved = tallies.get(run.run_id, (0, 0))
        item = schemas.HubRunOut.model_validate(run)
        item.asset_count = total
        item.approved_count = approved
        item.approved_label = f"{approved} of {total} approved"
        out.append(item)
    return out


@router.get("/clients/{client_id}/assets", response_model=List[schemas.HubAssetOut])
def list_assets(
    client_id: uuid.UUID,
    content_type: HubContentType = Query(..., description="The tab"),
    section: Optional[HubSection] = Query(None, description="The sub tab, except for blog"),
    period: Optional[str] = Query(None, description="'YYYY-MM', blog's sub tab"),
    version: Optional[int] = Query(
        None,
        ge=1,
        description="An older run to view. Omit for the newest, which is the default.",
    ),
    db: Session = Depends(get_db),
):
    """The items for one tab, each carrying the content of the version it shows.

    THE NEWEST RUN ONLY, unless `version` names an older one. Returning every
    run's assets was the original behaviour and it was wrong: re-running social
    for a client put v1 and v2 in one grid, forty cards with nothing to say
    which were the new ones, and the tab badge disagreed with the count on the
    page. The superseded runs are reachable from the run history, which is what
    the history is for.

    For blog the newest run is per month, because its sub tabs are the months.
    See _latest_run_ids.

    The content is joined in on active_version. Outer joined, not inner, because
    an asset whose version row is missing is a state worth seeing rather than
    silently dropping from the list.
    """
    shown = models.ContentAsset.active_version

    query = (
        db.query(
            models.ContentAsset,
            models.ContentRun.content_type,
            models.ContentAssetVersion.body,
            models.ContentAssetVersion.file_path,
        )
        .join(models.ContentRun, models.ContentAsset.run_id == models.ContentRun.run_id)
        .outerjoin(
            models.ContentAssetVersion,
            and_(
                models.ContentAssetVersion.asset_id == models.ContentAsset.asset_id,
                models.ContentAssetVersion.version == shown,
            ),
        )
        .filter(
            models.ContentAsset.client_id == client_id,
            models.ContentRun.content_type == content_type.value,
        )
    )

    if version is not None:
        query = query.filter(models.ContentRun.version == version)
    else:
        latest = _latest_run_ids(db, client_id)
        if not latest:
            return []
        query = query.filter(models.ContentRun.run_id.in_(latest))

    if section is not None:
        query = query.filter(models.ContentAsset.section == section.value)
    if period is not None:
        query = query.filter(models.ContentRun.period == period)

    rows = query.order_by(
        models.ContentRun.version.desc(),
        models.ContentAsset.position,
        models.ContentAsset.asset_id,
    ).all()

    return [
        _asset_out(asset, ct, body, file_path)
        for asset, ct, body, file_path in rows
    ]


# --------------------------------------------------------------------------
# One asset
# --------------------------------------------------------------------------


@router.get("/assets/{asset_id}", response_model=schemas.HubAssetDetailOut)
def get_asset(asset_id: uuid.UUID, db: Session = Depends(get_db)):
    """One item and every version of it, oldest first.

    `is_active` marks what ships, which is not always what the card is showing:
    previewing an older version is client side only and leaves nothing
    alone, so the panel needs both to label the history honestly.
    """
    asset = _get_asset(db, asset_id)
    return schemas.HubAssetDetailOut(
        asset=_one_asset_out(db, asset),
        active_version=asset.active_version,
        versions=[
            schemas.HubVersionOut(
                version=version.version,
                body=version.body,
                file_path=version.file_path,
                created_at=version.created_at,
                is_active=version.version == asset.active_version,
            )
            for version in asset.versions
        ],
    )


@router.post("/assets/{asset_id}/approve", response_model=schemas.HubAssetOut)
def approve_asset(
    asset_id: uuid.UUID,
    approved: bool = Query(True),
    db: Session = Depends(get_db),
):
    """Sign-off, the one piece of state the hub owns rather than copies.

    Never written back to a source table. The older tables record no approval
    for text at all, and adding one would change behaviour the existing routes
    depend on, so this is the record.

    Un-approving clears approved_at rather than keeping it, so the column can
    always be read as "when this was signed off" without checking status too.
    """
    asset = _get_asset(db, asset_id)
    asset.status = "approved" if approved else "review"
    asset.approved_at = datetime.now(timezone.utc) if approved else None
    db.commit()
    db.refresh(asset)
    return _one_asset_out(db, asset)


@router.post("/assets/{asset_id}/restore", response_model=schemas.HubAssetOut)
def restore_version(
    asset_id: uuid.UUID,
    version: int = Query(..., ge=1),
    db: Session = Depends(get_db),
):
    """Make an older version the one that ships.

    The only version state the database keeps, since previewing is client side.
    """
    asset = _get_asset(db, asset_id)
    _get_version(db, asset_id, version)
    asset.active_version = version
    db.commit()
    db.refresh(asset)
    return _one_asset_out(db, asset)




# --------------------------------------------------------------------------
# Chat, which belongs to a version rather than to an asset
# --------------------------------------------------------------------------


@router.get("/assets/{asset_id}/chat", response_model=List[schemas.HubChatMessageOut])
def list_chat(
    asset_id: uuid.UUID,
    version: Optional[int] = Query(None, ge=1, description="Defaults to the displayed version"),
    db: Session = Depends(get_db),
):
    """One version's conversation, oldest first.

    The version defaults to the one the card is showing, because that is the
    text the panel has open and asking for the thread of anything else would be
    a deliberate act.
    """
    asset = _get_asset(db, asset_id)
    version = version if version is not None else asset.active_version
    _get_version(db, asset_id, version)

    return (
        db.query(models.ContentAssetChat)
        .filter(
            models.ContentAssetChat.asset_id == asset_id,
            models.ContentAssetChat.version == version,
        )
        .order_by(
            models.ContentAssetChat.created_at, models.ContentAssetChat.message_id
        )
        .all()
    )


@router.post(
    "/assets/{asset_id}/chat",
    response_model=schemas.HubChatMessageOut,
    status_code=201,
)
def add_chat_message(
    asset_id: uuid.UUID,
    payload: schemas.HubChatMessageCreate,
    version: Optional[int] = Query(None, ge=1, description="Defaults to the displayed version"),
    db: Session = Depends(get_db),
):
    """Append a message to one version's thread.

    The version is checked before the insert. cg_asset_chats has a composite
    foreign key to (asset_id, version), so skipping the check turns a typo into
    an IntegrityError 500 that names a constraint instead of the parameter.
    """
    asset = _get_asset(db, asset_id)
    version = version if version is not None else asset.active_version
    _get_version(db, asset_id, version)

    message = models.ContentAssetChat(
        asset_id=asset_id,
        version=version,
        body=payload.body,
    )
    db.add(message)
    db.commit()
    db.refresh(message)
    return message


# --------------------------------------------------------------------------
# Sync
# --------------------------------------------------------------------------


@router.post("/sync", response_model=schemas.HubSyncOut)
def sync(db: Session = Depends(get_db)):
    """Re-derives content from the older tables. Idempotent, safe to call anytime.

    Content only. The client list is never copied, because HQ owns it.
    """
    return sync_all(db)


@router.get(
    "/clients/{client_id}/assets/by-slug/{slug}",
    response_model=schemas.HubAssetDetailOut,
)
def get_asset_by_slug(
    client_id: uuid.UUID,
    slug: str,
    db: Session = Depends(get_db),
):
    """One asset addressed the way a URL addresses it.

    No section parameter, because (client_id, slug) is unique by index. That is
    what lets /sg/logos/concept-1/image be a complete address: the logo routes
    carry no section, and requiring one here would have pushed a disambiguator
    into the query string where a shared link would lose it.

    Returned as the same detail shape as /assets/{asset_id}, so a page reached
    by slug and one reached by id render from identical data.
    """
    asset = (
        db.query(models.ContentAsset)
        .filter(
            models.ContentAsset.client_id == client_id,
            models.ContentAsset.slug == slug,
        )
        .first()
    )
    if asset is None:
        raise HTTPException(status_code=404, detail="Asset not found")
    return schemas.HubAssetDetailOut(
        asset=_one_asset_out(db, asset),
        active_version=asset.active_version,
        versions=[
            schemas.HubVersionOut(
                version=version.version,
                body=version.body,
                file_path=version.file_path,
                created_at=version.created_at,
                is_active=version.version == asset.active_version,
            )
            for version in sorted(asset.versions, key=lambda v: v.version)
        ],
    )


# --------------------------------------------------------------------------
# Per-section item counts
# --------------------------------------------------------------------------


@router.get("/settings", response_model=List[schemas.HubSectionDefaultOut])
def list_section_defaults(
    client_id: Optional[uuid.UUID] = Query(
        None, description="Omit for the house defaults; pass one for that client view."
    ),
    db: Session = Depends(get_db),
):
    """What each section resolves to, and where the number came from.

    One route for both levels rather than two. Without `client_id` these are
    the house defaults; with one they are what that client would actually get,
    each row saying whether it is inherited or overridden. The panel is the same
    panel either way, so it should not be two calls returning different shapes.
    """
    return [
        schemas.HubSectionDefaultOut(**row)
        for row in section_settings.describe(db, client_id)
    ]


@router.put("/settings/{section}", response_model=List[schemas.HubSectionDefaultOut])
def set_section_default(
    section: HubSection,
    payload: schemas.HubSectionDefaultIn,
    client_id: Optional[uuid.UUID] = Query(
        None, description="Omit to set the house default; pass one to override it."
    ),
    db: Session = Depends(get_db),
):
    """Sets one count. Returns the whole panel, not just the row that changed.

    The whole panel because a client override changes how its own row reads
    (`source` becomes `client`) and a house change moves every row that
    inherits it. Returning one row would leave the rest stale and force a
    refetch anyway.
    """
    try:
        section_settings.put(db, section.value, payload.item_count, client_id)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc
    return [
        schemas.HubSectionDefaultOut(**row)
        for row in section_settings.describe(db, client_id)
    ]


@router.delete("/settings/{section}", response_model=List[schemas.HubSectionDefaultOut])
def clear_section_default(
    section: HubSection,
    client_id: uuid.UUID = Query(
        ..., description="Required: only a client override can be cleared."
    ),
    db: Session = Depends(get_db),
):
    """Drops a client override so the section inherits the house default again.

    `client_id` is required rather than optional. Clearing a house default would
    leave the section on a constant in Python that the panel can neither show
    nor change, so the value would look stuck. There is nothing to fall back to
    below the house level.
    """
    section_settings.clear(db, section.value, client_id)
    return [
        schemas.HubSectionDefaultOut(**row)
        for row in section_settings.describe(db, client_id)
    ]


# --------------------------------------------------------------------------
# Generation
# --------------------------------------------------------------------------


#: Keys never handed back to a form.
#:
#: `prepared` and the intake products are derived, not typed. The rest is
#: bookkeeping from the sync: it records where a row came from in the v1 tables
#: and means nothing to someone filling in a form.
_DRAFT_HIDDEN = {
    "prepared",
    "sitemap_data",
    "meeting_insights",
    "resolved_industries",
    "status",
    "error_message",
    "note",
    "source_id",
    "source_table",
}


@router.get("/clients/{client_id}/draft", response_model=schemas.HubDraftOut)
def get_draft(
    client_id: uuid.UUID,
    content_type: HubContentType = Query(...),
    db: Session = Depends(get_db),
):
    """The brief the most recent run of this type used, for the form to open on.

    Returns an empty `source` rather than a 404 when the client has never had a
    run of this type. An empty form is the correct answer to "what did we use
    last time" when the answer is "nothing", and a 404 would make the form
    handle an error for the normal first-time case.

    Nothing here comes from the Command HQ export, which was asked for
    explicitly: the picker says who the run is for, the form says what to
    generate, and prefilling the second from the first put stale answers in
    front of someone who was there to type fresh ones.
    """
    run = (
        db.query(models.ContentRun)
        .filter(
            models.ContentRun.client_id == client_id,
            models.ContentRun.content_type == content_type.value,
        )
        .order_by(models.ContentRun.version.desc())
        .first()
    )
    if run is None:
        return schemas.HubDraftOut(content_type=content_type, source={})

    return schemas.HubDraftOut(
        content_type=content_type,
        source={
            key: value
            for key, value in (run.source or {}).items()
            if key not in _DRAFT_HIDDEN
        },
        run_id=run.run_id,
        version=run.version,
        created_at=run.created_at,
    )


@router.post(
    "/clients/{client_id}/runs", response_model=schemas.HubRunOut, status_code=202
)
def create_run(
    client_id: uuid.UUID,
    payload: schemas.HubRunCreate,
    background: BackgroundTasks,
    db: Session = Depends(get_db),
):
    """Books the run in, then generates behind it. Returns 202 with the run.

    202 rather than 201: the run exists, and the work it describes has not
    happened yet. A website run is up to seventeen agent calls, so doing it
    inside the request would hold the connection open for minutes and lose
    everything to the first timeout.

    The background task opens its own Session. Sharing this request Session
    would mean writing to it after the response closed it, which is the failure
    that produces assets vanishing on refresh.
    """
    try:
        run = content_run.create_run(
            db,
            client_id=client_id,
            content_type=payload.content_type.value,
            source=payload.source,
            period=payload.period,
            requested_by=payload.requested_by,
        )
    except content_run.RunError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    background.add_task(_execute_run, run.run_id)
    return schemas.HubRunOut(
        run_id=run.run_id,
        content_type=run.content_type,
        version=run.version,
        status=run.status,
        period=run.period,
        summary=run.summary,
        requested_by=run.requested_by,
        client_name=run.client_name,
        asset_count=0,
        approved_count=0,
        approved_label="",
        created_at=run.created_at,
    )


def _execute_run(run_id: uuid.UUID) -> None:
    """Runs one run to completion on its own Session.

    Swallows everything. This is a background task with nobody to raise to, and
    `execute` already settles the run status and summary, so an exception
    escaping here would only lose the log line. The rescue below exists for the
    case where `execute` itself blew up before it could settle anything, which
    would otherwise leave a row stuck on `generating` for ever.
    """
    db = SessionLocal()
    try:
        run = db.get(models.ContentRun, run_id)
        if run is None:
            logger.warning("content_run_vanished run_id=%s", run_id)
            return
        content_run.execute(db, run)
    except Exception:
        logger.exception("content_run_crashed run_id=%s", run_id)
        try:
            db.rollback()
            run = db.get(models.ContentRun, run_id)
            if run is not None and run.status in ("pending", "generating"):
                run.status = "failed"
                run.summary = "The run stopped unexpectedly. The log has the reason."
                db.commit()
        except Exception:
            logger.exception("content_run_status_rescue_failed run_id=%s", run_id)
    finally:
        db.close()


@router.post("/assets/{asset_id}/image", response_model=schemas.HubAssetOut)
def request_asset_image(
    asset_id: uuid.UUID,
    asset_type: str = Query("image", pattern="^(image|video)$"),
    db: Session = Depends(get_db),
):
    """Books the image or video that goes with an APPROVED content asset.

    The gate, enforced here and in the service. A run never produces artwork:
    copy is written first, a person reads it and approves it, and only then is
    there something worth illustrating. Refusing in the API as well as hiding
    the button matters because the button is not the only caller.

    Returns the booked asset with no version yet, so queued work is visible
    while it waits rather than appearing only when it is finished.
    """
    try:
        asset = content_run.request_image(db, asset_id, asset_type)
    except content_run.RunError as exc:
        raise HTTPException(status_code=409, detail=str(exc)) from exc
    return _one_asset_out(db, asset)
