"""Creates a run, fans its items out, and writes the assets as they land.

The one generic path. It knows about runs, assets and versions; it knows nothing
about services, reels or ad angles. Each content type contributes a planner in
`planners/`, which turns the run's frozen `source` into a list of Tasks, and the
orchestrator does the rest identically for all five.

Two rules are enforced here rather than in the planners, because a planner is
the wrong place to be trusted with either.

Images are never generated by a run. A run produces `type='content'` assets and
nothing else. Images and video are created afterwards, one at a time, by
`request_image`, which refuses unless the content it would illustrate is
approved. This is a server-side check, not a hidden button: copy that nobody has
read is exactly what you do not want a designer building artwork from, and the
first caller to hit the API directly would otherwise get it.

Assets are written as each item finishes, not at the end. `on_result` runs on
the orchestrator's own thread, so the Session is never shared with a worker, and
the practical effect is that the page fills in as the run goes and a crash half
way through keeps everything already done.
"""

from __future__ import annotations

import logging
import uuid
from datetime import datetime, timezone
from typing import Any, Callable, Dict, List, Optional

from sqlalchemy import func, select
from sqlalchemy.orm import Session

from app.models.content_generation.asset import ContentAsset, ContentAssetVersion
from app.models.content_generation.client import ContentClient
from app.models.content_generation.run import SECTIONS_BY_CONTENT_TYPE, ContentRun
from app.services import content_generation_settings as settings
from app.services.content_generation_sync import slugify
from app.services.content_run import planners
from app.services.content_run.tasks import Plan, TaskResult, run_tasks

logger = logging.getLogger(__name__)

#: Which asset types a run may create. Content only, deliberately: see the
#: module docstring. `request_image` is the only way an image row is made.
RUN_ASSET_TYPE = "content"


class RunError(Exception):
    """A run that could not be started. Distinct from a run that failed.

    The difference matters to the caller: this is a 4xx with a reason the
    operator can act on (no such client, nothing in the sitemap), whereas a run
    that started and then failed is a 200 with a run_id and a status.
    """


# --------------------------------------------------------------------------
# Creating the run
# --------------------------------------------------------------------------


def _next_version(db: Session, client_id: uuid.UUID, content_type: str) -> int:
    """The next version for this client and content type.

    max+1 read inside the same transaction as the insert. The unique constraint
    cg_runs_version_uq is what actually guarantees correctness under a race, and
    it is there because this read alone does not: two simultaneous requests both
    see the same max. The loser gets an IntegrityError, which the caller retries.
    """
    current = db.execute(
        select(func.max(ContentRun.version)).where(
            ContentRun.client_id == client_id,
            ContentRun.content_type == content_type,
        )
    ).scalar()
    return (current or 0) + 1


def create_run(
    db: Session,
    client_id: uuid.UUID,
    content_type: str,
    source: Dict[str, Any],
    period: Optional[str] = None,
    requested_by: Optional[str] = None,
) -> ContentRun:
    """Records the request and freezes its brief. Does not generate anything.

    Split from `execute` so the API can return a run_id immediately and the
    generation can happen behind it. A run that exists with status `pending` is
    a request someone can see; a run that only exists once generation finishes
    is a spinner with nothing behind it.

    `client_name` is not set: it is a generated column off source->>'client_name',
    so Postgres rejects any insert that names it.
    """
    if content_type not in SECTIONS_BY_CONTENT_TYPE:
        raise RunError(f"Unknown content type {content_type!r}.")

    client = db.get(ContentClient, client_id)
    if client is None:
        raise RunError(
            "That client has no record here yet. Command HQ owns the client "
            "list, so a client appears once it has had a run."
        )

    payload = dict(source or {})
    payload.setdefault("client_name", client.client_name)

    run = ContentRun(
        client_id=client_id,
        content_type=content_type,
        version=_next_version(db, client_id, content_type),
        status="pending",
        source=payload,
        period=period,
        requested_by=requested_by,
    )
    db.add(run)
    db.commit()
    db.refresh(run)
    # last_run_at needs no update here: the cg_runs_touch_client trigger has
    # already done it, which is the whole reason it is a trigger.
    logger.info(
        "content_run_created run_id=%s client=%s type=%s v%s",
        run.run_id,
        client_id,
        content_type,
        run.version,
    )
    return run


# --------------------------------------------------------------------------
# Executing it
# --------------------------------------------------------------------------


def execute(
    db: Session,
    run: ContentRun,
    on_progress: Optional[Callable[[int, int], None]] = None,
) -> ContentRun:
    """Plans, fans out, persists, reconciles, and settles the run's status.

    Never raises for a generation failure. A run whose items partly succeeded is
    `partial` and keeps what worked, because ten good posts are worth more than
    a clean error. Only a failure to plan at all produces `failed`.
    """
    # `generating` BEFORE planning, not after. Planning is not bookkeeping: it
    # is where a social run does almost all of its work, because the post and
    # review writers each produce their whole set in one call. A measured JK
    # Cooling run spent 180 of its 220 seconds in here, and setting the status
    # afterwards meant the panel showed `pending` with nothing on it for three
    # minutes, which reads as a run that never started.
    run.status = "generating"
    db.commit()

    counts = settings.resolve_for_content_type(db, run.content_type, run.client_id)
    plan: Plan = planners.plan_for(run.content_type, dict(run.source or {}), run.run_id, counts)

    if plan.error or not plan.tasks:
        run.status = "failed"
        run.summary = plan.error or "There was nothing to generate for this brief."
        db.commit()
        logger.warning("content_run_no_tasks run_id=%s %s", run.run_id, run.summary)
        return run

    # Whatever the planner derived that is worth keeping goes into `source`
    # before the fan-out, so a run that dies half way still has the brief its
    # finished items were written from.
    if plan.prepared:
        run.source = {**(run.source or {}), "prepared": plan.prepared}
        db.commit()

    total = len(plan.tasks)
    done = 0
    by_key: Dict[str, ContentAsset] = {}

    def persist(result: TaskResult) -> None:
        nonlocal done
        done += 1
        asset = _write_asset(db, run, result)
        if asset is not None:
            by_key[result.task.key] = asset
        if on_progress is not None:
            on_progress(done, total)

    logger.info(
        "content_run_start run_id=%s type=%s tasks=%s", run.run_id, run.content_type, total
    )
    results = run_tasks(plan.tasks, on_result=persist)

    if plan.reconcile is not None:
        _apply_reconcile(db, run, plan, results, by_key)

    ok = sum(1 for r in results if r.ok)
    run.status = "complete" if ok == total else ("failed" if ok == 0 else "partial")
    run.summary = _summary(ok, total, run.content_type)
    db.commit()
    logger.info(
        "content_run_done run_id=%s status=%s ok=%s/%s", run.run_id, run.status, ok, total
    )
    return run


def _summary(ok: int, total: int, content_type: str) -> str:
    """A sentence for the run history, not a status code.

    The history line is read by whoever is deciding whether to look at the run,
    so "10 of 12 written, 2 failed" answers that and "partial" does not.
    """
    noun = "item" if total == 1 else "items"
    if ok == total:
        return f"{total} {noun} written."
    if ok == 0:
        return f"Nothing was written. All {total} {noun} failed."
    return f"{ok} of {total} {noun} written, {total - ok} failed."


def _write_asset(db: Session, run: ContentRun, result: TaskResult) -> Optional[ContentAsset]:
    """One asset and its first version, committed on its own.

    Committed per item rather than once at the end so a later failure cannot
    roll back work that succeeded. That is the same reason the run status is
    only settled after the fan-out.

    A failed task gets no asset. An asset row with no version would render as a
    blank card, and the reason for the failure is in the run summary and the log
    where it can actually be read.
    """
    if not result.ok:
        logger.warning(
            "content_asset_skipped run_id=%s key=%s %s",
            run.run_id,
            result.task.key,
            result.error,
        )
        return None

    task = result.task
    asset = ContentAsset(
        run_id=run.run_id,
        client_id=run.client_id,
        section=task.section,
        type=RUN_ASSET_TYPE,
        position=task.position,
        title=task.title,
        status="review",
        active_version=1,
        slug=_unique_slug(db, run.client_id, task),
    )
    db.add(asset)
    db.flush()
    db.add(ContentAssetVersion(asset_id=asset.asset_id, version=1, body=result.body))
    db.commit()
    return asset


def _unique_slug(db: Session, client_id: uuid.UUID, task) -> str:
    """A URL segment unique within the client, which is what the index requires.

    cg_assets_slug_uq is on (client_id, slug), not (client_id, section, slug),
    so two sections cannot share a slug. That is deliberate and load bearing:
    a logo URL carries no section, so /sg/logos/concept-1/image has to be
    sufficient on its own. The suffix loop is what makes a second
    "roof-repairs" into "roof-repairs-2".
    """
    base = slugify(task.title, fallback=f"{task.section}-{task.position + 1}")
    candidate = base
    suffix = 1
    while True:
        clash = db.execute(
            select(ContentAsset.asset_id).where(
                ContentAsset.client_id == client_id, ContentAsset.slug == candidate
            )
        ).first()
        if clash is None:
            return candidate
        suffix += 1
        candidate = f"{base}-{suffix}"


def _apply_reconcile(
    db: Session,
    run: ContentRun,
    plan: Plan,
    results: List[TaskResult],
    by_key: Dict[str, ContentAsset],
) -> None:
    """Runs the planner's reconcile and stores each change as version 2.

    A new version rather than an edit of version 1. The reconcile rewrote copy
    that a person may already have opened, so the original has to stay
    readable and restorable; that is what the version history is for. It also
    means the diff between what the writer produced and what the dedupe pass
    changed is inspectable, which matters the first time it gets something
    wrong.
    """
    try:
        changed = plan.reconcile(results) or {}
    except Exception:
        logger.exception("content_reconcile_failed run_id=%s", run.run_id)
        return

    for key, body in changed.items():
        asset = by_key.get(key)
        if asset is None:
            continue
        version = (asset.active_version or 1) + 1
        db.add(ContentAssetVersion(asset_id=asset.asset_id, version=version, body=body))
        asset.active_version = version
        db.commit()

    if changed:
        logger.info(
            "content_reconcile_applied run_id=%s assets=%s", run.run_id, len(changed)
        )


# --------------------------------------------------------------------------
# Images, which a run never creates
# --------------------------------------------------------------------------


def request_image(
    db: Session, asset_id: uuid.UUID, asset_type: str = "image"
) -> ContentAsset:
    """Creates the image asset that goes with an approved content asset.

    The gate. Refuses unless the content asset is `approved`, so artwork is
    only ever built from copy a person has read and signed off. Enforced here
    rather than by hiding the button, because the button is not the only caller.

    Returns the image asset row with no version yet: this books the work in and
    makes it visible. The generator fills version 1 in afterwards.
    """
    if asset_type not in ("image", "video"):
        raise RunError(f"{asset_type!r} is not something to request. Use image or video.")

    content = db.get(ContentAsset, asset_id)
    if content is None:
        raise RunError("That asset does not exist.")
    if content.type != "content":
        raise RunError(
            "Images are requested against a content asset, not against another "
            "image."
        )
    if content.status != "approved":
        raise RunError(
            "This content is not approved yet. Approve the copy first, then the "
            "image can be made from it."
        )

    existing = db.execute(
        select(ContentAsset).where(
            ContentAsset.run_id == content.run_id,
            ContentAsset.section == content.section,
            ContentAsset.position == content.position,
            ContentAsset.type == asset_type,
        )
    ).scalar_one_or_none()
    if existing is not None:
        return existing

    image = ContentAsset(
        run_id=content.run_id,
        client_id=content.client_id,
        section=content.section,
        type=asset_type,
        position=content.position,
        title=content.title,
        status="generating",
        active_version=1,
        # No slug. The content asset owns the client-unique slug for this
        # position, and the URL contract already carries the type as its own
        # segment: /sg/logos/concept-1/content and /sg/logos/concept-1/image
        # are the same slug, different type.
        slug=None,
    )
    db.add(image)
    db.commit()
    db.refresh(image)
    logger.info(
        "content_image_requested asset_id=%s from=%s type=%s",
        image.asset_id,
        asset_id,
        asset_type,
    )
    return image


def generate(
    db: Session,
    client_id: uuid.UUID,
    content_type: str,
    source: Dict[str, Any],
    period: Optional[str] = None,
    requested_by: Optional[str] = None,
) -> ContentRun:
    """create_run then execute, for callers that want the whole thing.

    Synchronous, which is fine for a background task and wrong for a request
    handler: a website run is seventeen agent calls. The router creates the run,
    returns it, and calls this from a background task.
    """
    run = create_run(db, client_id, content_type, source, period, requested_by)
    return execute(db, run)
