"""initial schema

Revision ID: b08c26281334
Revises: 
Create Date: 2026-07-23 14:25:03.210960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b08c26281334'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_angle_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('usps', sa.Text(), nullable=False),
    sa.Column('offers', sa.Text(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('service_content', sa.Text(), nullable=False),
    sa.Column('industry', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_angle_requests_id'), 'ad_angle_requests', ['id'], unique=False)
    op.create_table('ad_angles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['ad_angle_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_angles_id'), 'ad_angles', ['id'], unique=False)
    op.create_index(op.f('ix_ad_angles_request_id'), 'ad_angles', ['request_id'], unique=False)
    op.create_table('angle_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('angle_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['angle_id'], ['ad_angles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_angle_chat_messages_angle_id'), 'angle_chat_messages', ['angle_id'], unique=False)
    op.create_index(op.f('ix_angle_chat_messages_id'), 'angle_chat_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_angle_chat_messages_id'), table_name='angle_chat_messages')
    op.drop_index(op.f('ix_angle_chat_messages_angle_id'), table_name='angle_chat_messages')
    op.drop_table('angle_chat_messages')
    op.drop_index(op.f('ix_ad_angles_request_id'), table_name='ad_angles')
    op.drop_index(op.f('ix_ad_angles_id'), table_name='ad_angles')
    op.drop_table('ad_angles')
    op.drop_index(op.f('ix_ad_angle_requests_id'), table_name='ad_angle_requests')
    op.drop_table('ad_angle_requests')
    # ### end Alembic commands ###
