"""add website content generation tables

Three tables behind the "Website Content Generation (V7)" n8n workflow, which
kept nothing of its own: its form fed straight into the agents and the finished
markdown was POSTed to a Zapier webhook, so a run could not be re-read, re-run
or audited afterwards.

  website_content_requests   the brief, plus the intake work that shaped it --
                             the meeting analysis, the parsed sitemap and the
                             resolved industry list, all of which the workflow
                             used once and discarded
  website_sections           the six delivered sections, one row each, holding
                             both the shipped markdown and the pre-refinement
                             draft it came from
  website_refinement_rounds  one row per Critic -> Refiner -> Evaluator pass.
                             In n8n each pass overwrote the last inside the
                             loop, so "what did the critic object to" was
                             unanswerable once a run finished.

Additive only: no existing table is touched.

Revision ID: b43f920701eb
Revises: a7c3e91b4d20
Create Date: 2026-08-25 17:44:16.008372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b43f920701eb'
down_revision: Union[str, None] = 'a7c3e91b4d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website_content_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('state_province_region', sa.String(), nullable=False),
    sa.Column('zip_postal_code', sa.String(), nullable=False),
    sa.Column('usps', sa.Text(), nullable=False),
    sa.Column('sitemap_text', sa.Text(), nullable=False),
    sa.Column('industries', sa.Text(), nullable=True),
    sa.Column('other_industries', sa.Text(), nullable=True),
    sa.Column('fathom_meeting_1_url', sa.String(), nullable=True),
    sa.Column('fathom_meeting_2_url', sa.String(), nullable=True),
    sa.Column('fathom_meeting_3_url', sa.String(), nullable=True),
    sa.Column('loom_1_summary', sa.Text(), nullable=True),
    sa.Column('loom_1_transcript', sa.Text(), nullable=True),
    sa.Column('loom_2_summary', sa.Text(), nullable=True),
    sa.Column('loom_2_transcript', sa.Text(), nullable=True),
    sa.Column('loom_3_summary', sa.Text(), nullable=True),
    sa.Column('loom_3_transcript', sa.Text(), nullable=True),
    sa.Column('meeting_insights', sa.Text(), nullable=True),
    sa.Column('sitemap_data', sa.Text(), nullable=True),
    sa.Column('resolved_industries', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_content_requests_id'), 'website_content_requests', ['id'], unique=False)
    op.create_table('website_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('section_key', sa.String(), nullable=False),
    sa.Column('section_title', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('draft', sa.Text(), nullable=True),
    sa.Column('blog_industry', sa.String(), nullable=True),
    sa.Column('blog_service', sa.String(), nullable=True),
    sa.Column('blog_titles', sa.Text(), nullable=True),
    sa.Column('blog_keywords', sa.Text(), nullable=True),
    sa.Column('refinement_turns', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('verdict_reason', sa.Text(), nullable=True),
    sa.Column('checks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['website_content_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'section_key', name='uq_website_sections_request_key')
    )
    op.create_index(op.f('ix_website_sections_id'), 'website_sections', ['id'], unique=False)
    op.create_index(op.f('ix_website_sections_request_id'), 'website_sections', ['request_id'], unique=False)
    op.create_table('website_refinement_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('turn', sa.Integer(), nullable=False),
    sa.Column('critic_report', sa.Text(), nullable=True),
    sa.Column('refined_content', sa.Text(), nullable=True),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('checks', sa.Text(), nullable=True),
    sa.Column('carry_forward', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['website_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_refinement_rounds_id'), 'website_refinement_rounds', ['id'], unique=False)
    op.create_index(op.f('ix_website_refinement_rounds_section_id'), 'website_refinement_rounds', ['section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_website_refinement_rounds_section_id'), table_name='website_refinement_rounds')
    op.drop_index(op.f('ix_website_refinement_rounds_id'), table_name='website_refinement_rounds')
    op.drop_table('website_refinement_rounds')
    op.drop_index(op.f('ix_website_sections_request_id'), table_name='website_sections')
    op.drop_index(op.f('ix_website_sections_id'), table_name='website_sections')
    op.drop_table('website_sections')
    op.drop_index(op.f('ix_website_content_requests_id'), table_name='website_content_requests')
    op.drop_table('website_content_requests')
    # ### end Alembic commands ###
