"""add logo generation request tables

Revision ID: cb476f3e95eb
Revises: f6a7b8c9d0e1
Create Date: 2026-08-04 15:41:49.152652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb476f3e95eb'
down_revision: Union[str, None] = 'f6a7b8c9d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logo_from_previous_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logo_path', sa.String(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('fathom_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logo_from_previous_requests_id'), 'logo_from_previous_requests', ['id'], unique=False)
    op.create_table('logo_from_scratch_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('usps', sa.Text(), nullable=False),
    sa.Column('fathom_url', sa.String(), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logo_from_scratch_requests_id'), 'logo_from_scratch_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logo_from_scratch_requests_id'), table_name='logo_from_scratch_requests')
    op.drop_table('logo_from_scratch_requests')
    op.drop_index(op.f('ix_logo_from_previous_requests_id'), table_name='logo_from_previous_requests')
    op.drop_table('logo_from_previous_requests')
    # ### end Alembic commands ###
