"""add use_ai_suggestion to logo request tables

Revision ID: e3db81bd1e02
Revises: cb476f3e95eb
Create Date: 2026-08-04 17:05:20.202658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3db81bd1e02'
down_revision: Union[str, None] = 'cb476f3e95eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'logo_from_previous_requests',
        sa.Column('use_ai_suggestion', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'logo_from_scratch_requests',
        sa.Column('use_ai_suggestion', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('logo_from_scratch_requests', 'usps',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logo_from_scratch_requests', 'usps',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('logo_from_scratch_requests', 'use_ai_suggestion')
    op.drop_column('logo_from_previous_requests', 'use_ai_suggestion')
    # ### end Alembic commands ###
