"""add fathom_transcript to logo request tables

Revision ID: eb05a60f3542
Revises: fd8ada23df9d
Create Date: 2026-08-05 16:13:29.049612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb05a60f3542'
down_revision: Union[str, None] = 'fd8ada23df9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logo_from_previous_requests', sa.Column('fathom_transcript', sa.Text(), nullable=True))
    op.add_column('logo_from_scratch_requests', sa.Column('fathom_transcript', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logo_from_scratch_requests', 'fathom_transcript')
    op.drop_column('logo_from_previous_requests', 'fathom_transcript')
    # ### end Alembic commands ###
