"""add logo image versions and chat messages

Revision ID: fd8ada23df9d
Revises: e3db81bd1e02
Create Date: 2026-08-04 17:21:36.425673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8ada23df9d'
down_revision: Union[str, None] = 'e3db81bd1e02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logo_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scratch_request_id', sa.Integer(), nullable=True),
    sa.Column('previous_request_id', sa.Integer(), nullable=True),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['previous_request_id'], ['logo_from_previous_requests.id'], ),
    sa.ForeignKeyConstraint(['scratch_request_id'], ['logo_from_scratch_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logo_images_id'), 'logo_images', ['id'], unique=False)
    op.create_index(op.f('ix_logo_images_previous_request_id'), 'logo_images', ['previous_request_id'], unique=False)
    op.create_index(op.f('ix_logo_images_scratch_request_id'), 'logo_images', ['scratch_request_id'], unique=False)
    op.create_table('logo_image_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logo_image_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('attachment_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['logo_image_id'], ['logo_images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logo_image_chat_messages_id'), 'logo_image_chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_logo_image_chat_messages_logo_image_id'), 'logo_image_chat_messages', ['logo_image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logo_image_chat_messages_logo_image_id'), table_name='logo_image_chat_messages')
    op.drop_index(op.f('ix_logo_image_chat_messages_id'), table_name='logo_image_chat_messages')
    op.drop_table('logo_image_chat_messages')
    op.drop_index(op.f('ix_logo_images_scratch_request_id'), table_name='logo_images')
    op.drop_index(op.f('ix_logo_images_previous_request_id'), table_name='logo_images')
    op.drop_index(op.f('ix_logo_images_id'), table_name='logo_images')
    op.drop_table('logo_images')
    # ### end Alembic commands ###
