INDUSTRIES = [
    "Boiler",
    "Solar",
    "EV Charger",
    "ASHP",
    "Air Con",
    "ECO4",
    "Doors & Windows",
    "Damp Proofing",
    "Insulation",
    "Verandas & Canopy",
    "Electrical",
    "Roofing",
    "Driveways & Patio",
    "Stairlifts & Homelifts",
    "Security Services",
    "Property Claims",
    "Property Maintenance",
    "Garden Rooms",
    "Bathroom Installation",
    "Kitchen Installation",
    "Building Constructions services",
    "Networking Services",
    "Swimming pool",
    "Wood Burning Stove",
    "Microcement",
    "Painting & Decorating",
    "Fire protection",
    "Plastering Services",
    "Skin Booster & PRP",
    "Television"
]
